# Generated by Django 5.0.8 on 2024-12-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_patient_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
